/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design System Colors
        'on-primary-fixed-variant': '#004785',
        'on-tertiary-container': '#f7fff1',
        'on-secondary-fixed': '#2e1500',
        'surface-tint': '#0060a8',
        secondary: '#8f4e00',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fc',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#ffb77b',
        'on-surface': '#191c1e',
        'primary-fixed-dim': '#a2c9ff',
        'on-secondary-container': '#623300',
        'surface-container': '#eceef1',
        'on-tertiary-fixed': '#002204',
        'primary-container': '#0077ce',
        'outline-variant': '#c0c7d4',
        surface: '#f7f9fc',
        'tertiary-fixed-dim': '#78dc77',
        'inverse-surface': '#2d3133',
        outline: '#707783',
        'tertiary-fixed': '#94f990',
        'secondary-container': '#ff8f06',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e6',
        'primary-fixed': '#d3e4ff',
        'surface-dim': '#d8dadd',
        error: '#ba1a1a',
        'on-primary-fixed': '#001c38',
        'surface-variant': '#e0e3e6',
        'inverse-primary': '#a2c9ff',
        'surface-container-high': '#e6e8eb',
        'secondary-fixed': '#ffdcc2',
        'on-background': '#191c1e',
        'tertiary-container': '#1e862d',
        tertiary: '#006b1b',
        'on-tertiary-fixed-variant': '#005313',
        primary: '#004785',
        'on-surface-variant': '#404752',
        'surface-container-low': '#f2f4f7',
        'inverse-on-surface': '#eff1f4',
        background: '#f7f9fc',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#6d3a00',
        'on-primary-container': '#fdfcff',
        // Legacy colors
        admin: '#1A1A1A',
        success: '#2D6A4F',
        warning: '#FBC02D',
        danger: '#9B2226',
        dangerAdmin: '#CC0000',
        dangerBorder: '#FFEEEE',
        bodyCustomer: '#F5F5F6',
        bodyAdmin: '#FAFAFA',
        textMain: '#1C1C1C',
        textAdmin: '#333333',
        placeholder: '#6E6E73',
        borderLight: '#D1D1D1',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Be Vietnam Pro'],
        display: ['Be Vietnam Pro'],
        body: ['Be Vietnam Pro'],
        label: ['Be Vietnam Pro'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        customer: '4px',
        admin: '2px',
      },
      letterSpacing: {
        btn: '0.5px',
      },
    },
  },
  plugins: [],
};
